name: MineFarm
version: '${project.version}'
main: me.past2l.minefarm.MineFarm
authors: [ Green0121, Past2l ]
description: Custom Plugin for MineFarm
website: https://github.com/past2l

commands:
  test:
    description: Command for Test plugin.
    permission: minefarm.test
  npc:
    description: Command for NPC plugin.
    permission: minefarm.npc
  gui:
    description: Command for GUI plugin.
    permission: minefarm.gui
  ender_chest:
    description: Command for Open Ender Chest.
    permission: minefarm.ender_chest
  admin:
    description: Command for Admin GUI.
    permission: minefarm.admin
  player:
    description: Command for Manage Player.
    permission: minefarm.player

permissions:
  minefarm.*:
    description: Gives access to all MineFarm Commands
    children:
      minefarm.test: true
      minefarm.npc: true
      minefarm.gui: true
      minefarm.ender_chest: true
      minefarm.admin: true
      minefarm.player: true
  minefarm.test:
    description: Give access to use MineFarm Test Command
    default: op
  minefarm.npc:
    description: Give access to use MineFarm NPC Command
    default: op
  minefarm.gui:
    description: Give access to use MineFarm GUI Command
    default: op
  minefarm.ender_chest:
    description: Give access to use MineFarm Chest Command
    default: op
  minefarm.admin:
    description: Give access to use MineFarm Admin Command
    default: op
  minefarm.player:
    description: Give access to use MineFarm Player Command
    default: op
